# Generated by Django 3.2 on 2023-10-12 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0002_remove_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatar.svg', upload_to='images'),
        ),
    ]
